# AMATH 301 - HW2
University of Washington\
Due 10/14/2021

In [1]:
import numpy as np
import scipy.linalg as la

## Problem 1

Given equations expanded and solved:

---
**Equation 1:**
$$
R_6I_1 + R_1(I_1-I_2) + R_2(I_1 - I_3) = V_1
$$
Expanded:
$$
(R_1 + R_2 + R_6)I_1 - R_1I_2 - R_2I_3 = V_1
$$
Solved for $I_1$:
$$
I_1 = \frac{V_1 + R_1I_2 + R_2I_3}{R_1 + R_2 + R_6}
$$

---
**Equation 2:**
$$
R_3I_2 + R_4(I_2-I_3) + R_1(I_2 - I_1) = V_2\\
$$
Expanded:
$$
(R_1 + R_3 + R_4)I_2 - R_1I_1 - R_4I_3 = V_2
$$

Solved for $I_2$:
$$
I_2 = \frac{V_2 + R_1I_1 + R_4I_3}{R_1 + R_3 + R_4}
$$

---
**Equation 3:**
$$
R_5I_3 + R_4(I_3-I_2) + R_2(I_3 - I_1) = V_2\\
$$
Expanded:
$$
(R_2 + R_4 + R_5)I_3 - R_2I_1 - R_4I_2 = V_2
$$

Solved for $I_2$:
$$
I_3 = \frac{V_2 + R_2I_1 + R_4I_2}{R_2 + R_4 + R_5}
$$

In [16]:
# Define resistance and voltage values
dv = 2
r1,r2,r3,r4,r5,r6,V1,v2,v3 = 20,10,25,10,30,40,range(0,100+dv,dv),0,200

A = np.array([[r1+r2+r6, -r1, -r2],
                [-r1, r1+r3+r4, -r4],
                [-r2, -r4, r2+r4+r5]])
display(A)
B = np.ones((3,1))
display(B)
display(A@B)

array([[ 70, -20, -10],
       [-20,  55, -10],
       [-10, -10,  50]])

array([[1.],
       [1.],
       [1.]])

array([[40.],
       [25.],
       [30.]])

In [3]:
def LUSolve(P,L,U,b):
    y = la.solve_triangular(L,P.T@b, lower=True)
    x = la.solve_triangular(U,y)
    return x